# Generated by Django 6.1.1 on 2026-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('Cotton', 'Cotton'), ('Soybean', 'Soybean'), ('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Maize', 'Maize'), ('Other', 'Other')], default='Other', max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Healthy', max_length=20)),
                ('health_percentage', models.PositiveIntegerField(default=100)),
                ('planted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
